apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: audit-webhook-config
webhooks:
- name: audit.watson.org
  matchPolicy: Equivalent
  objectSelector:
    matchLabels:
      cp4d-audit: "yes"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    service:
      name: audit-webhook-service
      namespace: default
      path: "/add-sidecar"
      port: 443
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ3ekNDQXRjQ0ZCTlM0bXQ2bmt0SWpZZmtnYjA5Y2lFbjVPbEZNQTBHQ1NxR1NJYjNEUUVCRFFVQU1JR3oKTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNBd0NUbGt4RURBT0JnTlZCQWNNQjBOdmJHOW5ibVV4RHpBTgpCZ05WQkJFTUJqUXlOREkwTWpFVU1CSUdBMVVFQ1F3TFNHRnNiRzhnSURFMk1qRXhEREFLQmdOVkJBb01BMGxDClRURVBNQTBHQTFVRUN3d0dWMkYwYzI5dU1STXdFUVlEVlFRRERBcDNZWFJ6YjI0dWIzSm5NU293S0FZSktvWkkKaHZjTkFRa0JGaHRvWVhKcGJtRnlZWGxoYm1GdUxtMXZhR0Z1UUdsaWJTNWpiMjB3SGhjTk1qQXdPVEk0TVRrMQpOalU0V2hjTk1qQXhNREk0TVRrMU5qVTRXakNCc3pFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ01BazVaCk1SQXdEZ1lEVlFRSERBZERiMnh2WjI1bE1ROHdEUVlEVlFRUkRBWTBNalF5TkRJeEZEQVNCZ05WQkFrTUMwaGgKYkd4dklDQXhOakl4TVF3d0NnWURWUVFLREFOSlFrMHhEekFOQmdOVkJBc01CbGRoZEhOdmJqRVRNQkVHQTFVRQpBd3dLZDJGMGMyOXVMbTl5WnpFcU1DZ0dDU3FHU0liM0RRRUpBUlliYUdGeWFXNWhjbUY1WVc1aGJpNXRiMmhoCmJrQnBZbTB1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM2huSzltUkkKdTByT2pOZDhjOWlZaVI3dXArNWY5NVBGaEhLcTNlR1JTbWhqbWNOaVBhTjJHMEFLWUZkZEtXajh0YkNlbGg3ZwpDaVZpcFU3c2lEazMzRkRnWFFad0xrS2hMTThDWlllSm9TWmd3RUFUemZnWkltNHhxdWwrcmRHSXJIRkdOTW1KCjFlb1hCcEdEVks0NDR5SUhhdUx3elR4c3Q2MWZzdzlCeVR5M2N1UndFdC9DUkcvWE5ibVJ0Wi9HSm40dHJGcFQKMVpsYlRtVysvT08vS0R4UEZVcmJrQzNhNjB0NlZhNHJnckIrR0FxbTRLbmMvUmpYTy9EMEZuejE1bUFrNGtUeApaTjJDUEVpQWRpYytORE5GVW1Ra0IyajBqZjhraHNwQVVUdFdUS3REd1ZveStjS0p4bTl5MklJTmtMM3RJRzNJCis3VW1YakhiQXRZS1RRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkRRVUFBNElCQVFETmJoQ0Nob25YVURpZWRIR0oKbXNzZWJPWE9WYUpCTUhxc2NrVGowaisyMFRPS211c2xZU1hMTTJaSGpPNmNvdTB3Z1VZZ0VYZjBZRTJSdWRVdQpOQkZBMWRFcWVVV2FIZUxFeUwxS1AxWU1SWnlWWG9WOUZVMnBpS0hjK1hJSkVqSnB6ajg3Mm9PTmh4MHVpcUpZCkQ2eUVnWTJqVlZsWXdCWGE1K1JOdU1ROVJXemRkS1I2VzlSZExhdWdxbUJ6b2poYkx2MmJzVUJNSDE0SVZ4blMKSkFZYnh2NkdINmFzWXNPRkQySmRyMVI1MkJhZFNTaGxZd0lNb3NTTmNQQzIwajdZQjMxSmZOYitCU0trSEpSawpWZUYzWUk3YmtoaXBqajZhSncrZFJXckZaRVpjTXRNNm0xYlpvQ1JWWUhIcmUrbUxZVDhSaTF4bUVXaHpsMnZyCjlvTTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  failurePolicy: Ignore
